### PR TITLE
Added .htmlhintrc file

### LINKED ISSUE #57: Add a .htmlhintrc file
This file should:
- disable `spec-char-escape`
- disable `doctype-first`

### PR DESCRIPTION
**Pull request by MariamM110**
closes #57 

Should have `spec-char-escape` and `doctype-first` disabled when running actions

### CODE REVIEW

**Comment by SociableSteve** [comment]
I checked this out, then ran `npx htmlhint layouts/components/breadcrumbs.html`, no issues.
I removed the rule for `spec-char-escape`, ran the command, no issues reported.
I'd expected it to complain about `spec-char-escape` violations

**Comment by bp289** [comment]
> I checked this out, then ran `npx htmlhint layouts/components/breadcrumbs.html`, no issues. I removed the rule for `spec-char-escape`, ran the command, no issues reported. I'd expected it to complain about `spec-char-escape` violations

I think it needs to be set to true for it to complain just looked it up :  https://htmlhint.com/docs/user-guide/rules/spec-char-escape.

**Comment by MariamM110** [comment]
> I checked this out, then ran `npx htmlhint layouts/components/breadcrumbs.html`, no issues. I removed the rule for `spec-char-escape`, ran the command, no issues reported. I'd expected it to complain about `spec-char-escape` violations

Its weird, when i comment out the whole code it throws an error at me but when i comment out just one single line it throws no error?

**Comment by SociableSteve** [comment]
Supersceded by #63

**Pull request closed without merging**
